"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil


def test_audit_all_for_package_reports_no_violations():
    # Arrange
    has_scitex_dev = shutil.which("scitex-dev") is not None
    outcome = None
    # Act
    if has_scitex_dev:
        from scitex_dev.testing import audit_all_for_package
        outcome = audit_all_for_package('scitex-sh')
    # Assert
    assert outcome is None
